// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFITBu8opjxi_x3uFXLiasbKu8MoBM6o',
    appId: '1:789317746189:web:8ca084016d0ea437249f44',
    messagingSenderId: '789317746189',
    projectId: 'vriddhi-staff-billing',
    authDomain: 'vriddhi-staff-billing.firebaseapp.com',
    storageBucket: 'vriddhi-staff-billing.firebasestorage.app',
    measurementId: 'G-Y0KTR1WQYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQlgvABbPMvpXLG0T7qv7-5oEWiLEKdA',
    appId: '1:789317746189:android:3826059f06d7ef03249f44',
    messagingSenderId: '789317746189',
    projectId: 'vriddhi-staff-billing',
    storageBucket: 'vriddhi-staff-billing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6FZ-sm_xfodbqHVqDw1jPmJhJlSE7POI',
    appId: '1:789317746189:ios:ee06f2a378cf2b0a249f44',
    messagingSenderId: '789317746189',
    projectId: 'vriddhi-staff-billing',
    storageBucket: 'vriddhi-staff-billing.firebasestorage.app',
    iosBundleId: 'com.example.vriddhiStaffBillingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6FZ-sm_xfodbqHVqDw1jPmJhJlSE7POI',
    appId: '1:789317746189:ios:ee06f2a378cf2b0a249f44',
    messagingSenderId: '789317746189',
    projectId: 'vriddhi-staff-billing',
    storageBucket: 'vriddhi-staff-billing.firebasestorage.app',
    iosBundleId: 'com.example.vriddhiStaffBillingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFITBu8opjxi_x3uFXLiasbKu8MoBM6o',
    appId: '1:789317746189:web:36e6a677b42fe58d249f44',
    messagingSenderId: '789317746189',
    projectId: 'vriddhi-staff-billing',
    authDomain: 'vriddhi-staff-billing.firebaseapp.com',
    storageBucket: 'vriddhi-staff-billing.firebasestorage.app',
    measurementId: 'G-GB5WYCJJWK',
  );
}
